version: '2'
services:
  kiptender-app:
    image: kiptender
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kiptender-postgresql:5432/kiptender
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  kiptender-postgresql:
    extends:
      file: postgresql.yml
      service: kiptender-postgresql
