version: '2'
services:
  kiptender-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/kiptender/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kiptender
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
